export const allProducts = [
  {
    id: 1,
    title: "Combination Windows",
    createdAt: "12 october 2022",
    price: "$ 520,00",
    images: [
      "/images/p1.jpg",
      "/images/p2.jpg",
      "/images/p3.jpg",
      "/images/p4.jpg",
    ],
    desc: "The tilt & turn windows are one of the most versatile windows available in the market",
    addiInfo: [
      {
        weigth: "0.3kg",
        dimentions: "15*10*1cm",
        colours: "black,brown,white",
        material: "metal",
      },
    ],
    reviews: "0",
    sku: 12,
    categories: "Fashion, Style",
  },
  {
    id: 2,
    title: "Tilt & Turn Windows",
    createdAt: "12 october 2022",
    price: "$ 520,00",
    images: [
      "/images/p1.jpg",
      "/images/p2.jpg",
      "/images/p3.jpg",
      "/images/p4.jpg",
    ],
    desc: "The tilt & turn windows are one of the most versatile windows available in the market",
    addiInfo: [
      {
        weigth: "0.3kg",
        dimentions: "15*10*1cm",
        colours: "black,brown,white",
        material: "metal",
      },
    ],
    reviews: "0",
    sku: 12,
    categories: "Fashion, Style",
  },
  {
    id: 3,
    title: "Sliding Doors and Windows",
    createdAt: "12 october 2022",
    price: "$ 520,00",
    images: [
      "/images/p1.jpg",
      "/images/p2.jpg",
      "/images/p3.jpg",
      "/images/p4.jpg",
    ],
    desc: "The tilt & turn windows are one of the most versatile windows available in the market",
    addiInfo: [
      {
        weigth: "0.3kg",
        dimentions: "15*10*1cm",
        colours: "black,brown,white",
        material: "metal",
      },
    ],
    reviews: "0",
    sku: 12,
    categories: "Fashion, Style",
  },
  {
    id: 4,
    title: "Specialised Windows",
    createdAt: "12 october 2022",
    price: "$ 520,00",
    images: [
      "/images/p1.jpg",
      "/images/p2.jpg",
      "/images/p3.jpg",
      "/images/p4.jpg",
    ],
    desc: "The tilt & turn windows are one of the most versatile windows available in the market",
    addiInfo: [
      {
        weigth: "0.3kg",
        dimentions: "15*10*1cm",
        colours: "black,brown,white",
        material: "metal",
      },
    ],
    reviews: "0",
    sku: 12,
    categories: "Fashion, Style",
  },
];
